iwbt/models/__init__.py
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()

class Model(object):

    @property
    def shallow_json(self):
        return {k: v for k, v in self.__dict__.iteritems() if k not in "_sa_instance_state"}

iwbt/models/rivers.py
"""
    River Module contains class River
    Interacts with dataBase, Model for creating, accessing, and updating entries in Iwbt.Rivers
"""
from datetime import datetime
from sqlalchemy import Column, DateTime, Float, ForeignKey, Integer, String, Table, UniqueConstraint
from sqlalchemy.orm import relationship
from . import Base, Model


associate_user_favorites = Table('FavoriteRivers', Base.metadata,
                                 Column('id', Integer, primary_key=True),
                                 Column('user_id', Integer, ForeignKey('Users.id')),
                                 Column('river_id', Integer, ForeignKey('Rivers.id')))


class Area(Base, Model):
    __tablename__ = 'Areas'
    __table_args__ = (UniqueConstraint('name', name='_area_name_uc'),)
    id = Column(Integer, primary_key=True)
    name = Column(String(64), nullable=False)
    created = Column(DateTime, default=datetime.now)
    updated = Column(DateTime, default=datetime.now, onupdate=datetime.now)

    rivers = relationship('River', backref='area', cascade="all, delete, delete-orphan")
    sections = relationship('Section', backref='area', cascade="all, delete, delete-orphan")

    def __repr__(self):
        return "<Area: %r>" % self.name


class Gauge(Base, Model):
    __tablename__ = 'Gauges'
    id = Column(Integer, primary_key=True)
    usgs_id = Column(Integer, nullable=True)
    name = Column(String(64), nullable=False)
    river_id = Column(Integer, ForeignKey('Rivers.id'))
    created = Column(DateTime, default=datetime.now)
    updated = Column(DateTime, default=datetime.now, onupdate=datetime.now)

    river = relationship('River', backref='gauges', uselist=False)
    data = relationship('GaugeData', backref="gauge", order_by="desc(GaugeData.timestamp)")

    @property
    def current_level(self):
        return self.data[0]

    def get_current_flow(self, flow_type='level'):
        """ method to get current flow from USGS.
        :param flow_type: 'level' or 'flow' -- return level in feet or flow in CFS """
        return 100

    def __repr__(self):
        return "<Gauge: %r>" % self.name


class GaugeData(Base, Model):
    __tablename__ = 'GaugeData'
    __table_args__ = (UniqueConstraint('gauge_id', 'timestamp', name="UQ_GaugeData_gauge_id__timestamp"), )
    id = Column(Integer, primary_key=True)
    gauge_id = Column(Integer, ForeignKey('Gauges.id'))
    timestamp = Column(DateTime, default=datetime.now)
    retrieved = Column(DateTime, default=datetime.now)
    level = Column(Float)
    flow_cfs = Column(Float)

    def __repr__(self):
        return "<GaugeData: %r (%r)>" % (self.gauge.name, self.timestamp.strftime('%Y-%m-%d %H:%M:%S'))


class Rapid(Base, Model):
    __tablename__ = 'Rapids'
    id = Column(Integer, primary_key=True)
    name = Column(String(64), nullable=False)
    river_id = Column(Integer, ForeignKey('Rivers.id'), nullable=False)
    section_id = Column(Integer, ForeignKey('Sections.id'), nullable=False)
    rating = Column(Float)
    created = Column(DateTime, default=datetime.now)
    updated = Column(DateTime, default=datetime.now, onupdate=datetime.now)

    def __repr__(self):
        return "<Rapid: %r on %r>" % (self.name, self.river.name)


class River(Base, Model):
    __tablename__ = 'Rivers'
    id = Column(Integer, primary_key=True)
    name = Column(String(64), nullable=False)
    area_id = Column(Integer, ForeignKey('Areas.id'))
    created = Column(DateTime, default=datetime.now)
    updated = Column(DateTime, default=datetime.now, onupdate=datetime.now)

    rapids = relationship('Rapid', backref='river', cascade="all, delete, delete-orphan")
    sections = relationship('Section', backref='river', cascade="all, delete, delete-orphan")

    @property
    def primary_gauge(self):
        if self.gauges:
            return self.gauges[0]
        else:
            return None

    @property
    def json(self):
        json = {k: v for k, v in self.__dict__.iteritems() if k not in "_sa_instance_state"}
        if self.area:
            json['area'] = self.area.shallow_json
        if self.rapids:
            json['rapids'] = [r.shallow_json for r in self.rapids]
        if self.primary_gauge:
            json['gauge'] = self.primary_gauge.shallow_json
        if self.sections:
            json['sections'] = [s.shallow_json for s in self.sections]
        return json

    @property
    def current_data(self):
        if self.primary_gauge:
            return {'level': self.primary_gauge.current_level.level,
                    'flow': self.primary_gauge.current_level.flow_cfs,
                    'timestamp': self.primary_gauge.current_level.timestamp }
        return {'flow': None, 'level': None, 'timestamp': datetime.now()}

    def __repr__(self):
        return "<River: %r>" % (self.name)



class Section(Base, Model):
    __tablename__ = 'Sections'
    id = Column(Integer, primary_key=True)
    name = Column(String(64), nullable=False)
    area_id = Column(Integer, ForeignKey('Areas.id'))
    river_id = Column(Integer, ForeignKey('Rivers.id'), nullable=False)
    gauge_id = Column(Integer, ForeignKey('Gauges.id'))
    created = Column(DateTime, default=datetime.now)
    updated = Column(DateTime, default=datetime.now, onupdate=datetime.now)

    rapids = relationship('Rapid', backref='section', cascade="all, delete, delete-orphan")
    gauge = relationship('Gauge', backref='sections', uselist=False)

    def __repr__(self):
        return "<Section: %r %r>" % (self.river.name, self.name)

iwbt/models/weather.py
"""
    Weather Module contains data models for precipitation and associated data
"""
from datetime import datetime
from sqlalchemy import Column, DateTime, Float, ForeignKey, Integer, String, Table
from sqlalchemy.orm import relationship
from . import Base, Model


class WeatherStation(Base):
    __tablename__ = 'WeatherStations'
    id = Column(Integer, primary_key=True)
    source_id = Column(Integer, ForeignKey('WeatherSources.id'))
    latitude = Column(Float)
    longitude = Column(Float)

iwbt/blueprints/social/forms.py
from flask_wtf import FlaskForm
from wtforms import PasswordField, StringField, SubmitField
from wtforms.validators import DataRequired, EqualTo

class LoginForm(FlaskForm):
    alias = StringField('User Name', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    submit = SubmitField('Sign In')


class SignUpForm(FlaskForm):
    alias = StringField('User Name', validators=[DataRequired()])
    first_name = StringField('First Name', validators=[DataRequired()])
    last_name = StringField('Last Name', validators=[DataRequired()])
    email = StringField('Email', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired(), EqualTo('confirm', message='Passwords must match')])
    confirm = PasswordField('Confirm Password', validators=[DataRequired()])
    submit = SubmitField('Sign Me Up!')

iwbt/__init__.py
import os

from flask import Flask, g
from flask_bootstrap import Bootstrap
from flask_login import LoginManager
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker

from config import config
from .models import Base
from .models.social import User

login_manager = LoginManager()
bootstrap = Bootstrap()

def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])

    bootstrap.init_app(app)
    login_manager.init_app(app)

    from iwbt.blueprints.api_01 import api_01
    from . blueprints.main.views import main
    from . blueprints.rivers.views import rivers
    from . blueprints.social.views import social

    app.register_blueprint(rivers, url_prefix='/river')
    app.register_blueprint(social, url_prefix='/user')
    app.register_blueprint(main, url_prefix='/')
    app.register_blueprint(api_01, url_prefix='/api/v1.0')

    with app.app_context():
        get_db(app)


    @login_manager.user_loader
    def load_user(user_id):
        session = get_session(app)
        return session.query(User).filter(User.id == user_id).first()


    return app


def get_db(app):
    if not hasattr(g, 'dbcon'):
        g.dbcon = connect(app)
    return g.dbcon


def get_session(app):
    Session = sessionmaker(bind=get_db(app))
    return Session()


def connect(app):
    if os.getenv('DATABASE_URL'):
        eng = create_engine(os.getenv('DATABASE_URL'))
    else:
        eng = create_engine(app.config['DATABASE_URI'])
    if app.config['CREATE_DB']:
        Base.metadata.create_all(eng)
    return eng

iwbt/blueprints/api_01/__init__.py
"""
    River-API Stuff
    ==========================================
    API code is organized into sections based on the resource. Each resource
    has the following mandatory methods.

    Create new instance of resource
    ------------------------------------------
      * URL:        /api/v1.0/resource
      * Method:     POST
      * Route:      create_resource()
      * Returns:    shallow JSON-serialization of successfully-added resource
      * Required:   True

    Get Single Resource by numeric identifier
    ------------------------------------------
      * URL:        /api/v1.0/resource/<int:resource_id>
      * Method:     GET
      * Route:      read_resource_by_id(resource_id)
      * Returns:    single JSON-serialized object
      * Required:   True

    Get single resource by name string
    ------------------------------------------
      * URL:        /api/v1.0/resource/<string:resource_name>
      * Method:     GET
      * Route:      read_resource_by_name(resource_name)
      * Returns:    full JSON-serialized object
      * Required:   False
      * Note:       This only really applies to things that one may want to
                    look up by name, like River ...
                    top-level items.

    Get all resources of a particular type
    ------------------------------------------
      * URL:        /api/v1.0/resources/
      * Method:     GET
      * Route:      read_resources()
      * Returns:    array of JSON-serialized objects
      * Required:   True

    Update single resource by numeric identifier
    ------------------------------------------
      * URL:        /api/v1.0/resource/<int:resource_id>
      * Method:     PUT
      * Route:      update_resource(resource_id)
      * Returns:    shallow JSON-serialization of successfully-updated
                    resource instance
      * Required:   True

    Delete single resource by numeric identifier
    ------------------------------------------
      * URL:        /api/v1.0/resource/<int:resource_id>
      * Method:     DELETE
      * Route:      delete_resource(resource_id)
      * Returns:    200

    Full list of available resources
    ==========================================
    Each resource, along with a brief description, is provided below

    River
    Area
    Gauge
    GaugeData
    User

"""
from flask import Blueprint

api_01 = Blueprint('api_01', __name__, url_prefix='api/v1.0')


def verify(json, required_fields, allowed_fields=None):
    if not allowed_fields:
        allowed_fields = []
    allowed_fields += required_fields
    passes_required = verify_required_fields(json, required_fields)
    passes_allowed = verify_allowed_fields(json, allowed_fields)
    return passes_required * passes_allowed


def verify_required_fields(json, expected_fields):
    for field in expected_fields:
        try:
            assert field in json
        except AssertionError:
            return False
    return True


def verify_allowed_fields(json, allowed_fields):
    """ Ensure that no fields are passed that are not permitted for a
        given resource.
        :param json: dictionary of POST data passed in request
        :param allowed_fields: list of strings of acceptable parameters
        :return: True if all parameters are allowed; else False
    """
    for k in json.keys():
        if k not in allowed_fields:
            return False
    return True


def error_out(error):
    return error.json_response(True)


from . resources.areas import (create_area, read_area_by_id, read_areas,
                               update_area, delete_area)
from . resources.flow import (create_gauge_data, check_flow_by_river_id)
from . resources.gauges import (create_gauge, read_gauge_by_id, read_gauges,
                                update_gauge, delete_gauge)
from . resources.rapids import (create_rapid)
from . resources.rivers import (create_river, read_river_by_id,
                                read_river_by_name, read_rivers, update_river,
                                delete_river)
from . resources.sections import (create_section)
from . resources.users import (get_log_by_id, get_user_by_id,
                               get_user_by_alias, get_user_logs_by_id,
                               get_user_logs_by_alias, add_log_entry,
                               add_favorite_river)

iwbt/blueprints/main/views.py
from flask import Blueprint, current_app, render_template, send_file
from flask import redirect, request, url_for, flash

from flask_login import login_user, logout_user, login_required, current_user

from iwbt import get_session
from iwbt.models.rivers import *

main = Blueprint('main', __name__, url_prefix='')


@main.route('/')
def index():
    session = get_session(current_app)
    return render_template('index.html')



@main.route('ng')
def angular():
    return send_file('templates/ngtest.html')

iwbt/blueprints/rivers/views.py
from flask import Blueprint, current_app, render_template, redirect, request, url_for, flash

from flask_login import login_user, logout_user, login_required, current_user

from iwbt import get_session
from iwbt.models.rivers import *

rivers = Blueprint('rivers', __name__, url_prefix='river')


@rivers.route('/list')
def river_list():
    session = get_session(current_app)
    rivers = session.query(River).all()
    return render_template('rivers/river_list.html', rivers=rivers)


@rivers.route('/<int:river_id>')
def river_page(river_id):
    session = get_session(current_app)
    river = session.query(River).filter(River.id == river_id).first()
    return render_template('rivers/river_main.html', river=river)


@rivers.route('/favorites')
@login_required
def favorites():
    session = get_session(current_app)
    return render_template('rivers/river_list.html', rivers=current_user.favorite_rivers)

iwbt/blueprints/social/views.py
from flask import Blueprint, current_app, render_template, redirect, request, url_for, flash
from flask_login import login_user, logout_user, login_required, current_user
from sqlalchemy import or_

from iwbt import get_session
from iwbt.blueprints.social.forms import LoginForm, SignUpForm
from iwbt.models.social import *


social = Blueprint('social', __name__, url_prefix='user')


@social.route('/<user>')
def user_page(user):
    session = get_session(current_app)
    user = session.query(User).filter(User.alias == user).first()
    return render_template('social/user.html', user=user)


@social.route('/login', methods=['GET', 'POST'])
def login():
    session = get_session(current_app)
    login_form = LoginForm()

    if login_form.validate_on_submit():
        user = session.query(User).filter(User.alias == login_form.alias.data).first()
        if user is not None and user.verify_password(login_form.password.data):
            flash('You have successfully logged in to account %s' % user.alias, 'alert alert-success')
            login_user(user)
            return redirect(request.args.get('next') or url_for('social.user_page', user=user.alias))
        else:
            flash('UserName or Password Incorrect. Go Away :(', 'alert alert-danger')
        session.close()
        return redirect(url_for('social.login'))
    return render_template('social/login.html', form=login_form)


@social.route('/logout')
@login_required
def logout():
    logout_user()
    flash('You have been logged out', 'alert alert-danger')
    return redirect(url_for('river', name='Chattooga'))


@social.route('/signup', methods=['GET', 'POST'])
def sign_up():
    session = get_session(current_app)
    suf = SignUpForm()

    if suf.validate_on_submit():
        user = session.query(User).filter(or_(User.alias == suf.alias.data, User.email == suf.email.data)).first()
        if user:
            flash('User Name or Email already taken', 'alert alert-danger')
            return redirect("{{ url_for(social.sign_up) }}")
        flash('You have successfully signed up for an account with username %s' % suf.alias.data, 'alert alert-success')
        user = User(alias=suf.alias.data,
                    first_name=suf.first_name.data,
                    last_name=suf.last_name.data,
                    email=suf.email.data,
                    password=suf.password.data)
        session.add(user)
        session.commit()
        return redirect(url_for('social.login'))
    return render_template('social/signup.html', form=suf)


@social.route('/<alias>/log')
def paddle_log(alias):
    session = get_session(current_app)
    u = session.query(User).filter(User.alias == alias).first()
    return render_template('social/paddlelog.html', user=u)

iwbt/templates/social/login.html
{% extends "base.html" %}

{% block title %}<title>Login</title>{% endblock %}

{% block css %}
  {{ super() }}
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='CSS/login.css') }}">
{% endblock %}

{% block content %}
  <div id="logo"><img id="logo-img" src="{{ url_for('static', filename='IMG/logo.png') }}"></div>
  <div id="sign-in-box">
  <h3>Sign In</h3>
  <div id="standard-form">
    {{ wtf.quick_form(form) }}
  </div>
  <div class="divider divider-break">I'm New Here</div>
  <div><a href="{{ url_for('social.sign_up') }}" class="btn btn-secondary" id="sign-up" role="button">Sign Up</a></div>
  </div>
{% endblock %}

iwbt/templates/social/paddlelog.html
{% extends "base.html" %}

<title>{% block title %}IWBT{% endblock %}</title>

{% block content %}
<!--<div class="jumbotron container-fluid" style="background-image:url({{ img_wd }}images/Camping.jpg);
      background-repeat: no-repeat; background-size: 100%; height:900px"> -->
<div class="jumbotron container-fluid" style="background-image:url(http://www.betweenswims.com/2011_04_23_Tellico_BabyFalls1stRun01.jpg); background-repeat: no-repeat; background-size: 100%; height:900px">
  <h1 align="center" style="color:white;margin-top:45px">I Went Boating Today</h1>
  <p align="center", style="color:white">A One-Stop Shop for Online Whitewater Information.</p>
  <div class="row-fluid">
    <div class="span4"><span>{{ user.alias }}</span></div>
    <div class="span4"><span>Paddle Log</span></div>
  </div>
</div>
{% endblock %}

iwbt/templates/social/signup.html
{% extends "base.html" %}

{% block title %}<title>Sign Up</title>{% endblock %}

{% block css %}
  {{ super() }}
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='CSS/login.css') }}">
{% endblock %}

{% block content %}
<div id="logo"><img id="logo-img" src="{{ url_for('static', filename='IMG/logo.png') }}"></div>
<div id="sign-in-box">
  <h3>Sign Up</h3>
  <div id="standard-form">
    {{ wtf.quick_form(form) }}
  </div>
  <div class="divider divider-break">I'm New Here</div>
  <div><a href="{{ url_for('social.sign_up') }}" class="btn btn-secondary" id="sign-up" role="button">Sign Up</a></div>
</div>
{% endblock %}

iwbt/templates/social/user.html
{% extends "base.html" %}
<title>{% block title %}{{ user.alias }}{% endblock %}</title>

{% block css %}
{{ super() }}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='CSS/user.css') }}">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/sweetalert2/6.6.2/sweetalert2.min.css">
{% endblock %}

{% block scripts %}
{{ super() }}
<script src="https://cdn.jsdelivr.net/sweetalert2/6.6.2/sweetalert2.min.js"></script>
{% endblock %}

{% block content %}

<div class="container-fluid" id="page_head">
{% if user %}
  <h2 id="page_title">{{user.alias}}</h2>
  <div class="col-sm-6 col-md-12">
  <div class="col-sm-1 col-md-2"><img class="avatar" src="{{ url_for('static', filename="IMG/silhouette.png") }}"></div>
  <div class="col-sm-4 col-md-5"><p>
    The Mon Calamari were a bipedal, amphibious species with high-domed heads, webbed hands and large, goggle-like eyes.[1] In addition to being webbed, the Mon Calamari hand presented three suction-cup like holes on its palm, and featured five claw-tipped fingers: one opposable thumb, two long middle fingers, and two very short outer fingers.[2] Although they were shaped like flippers,[6] their feet could nevertheless fit into boots designed for human-like feet.[9] The females were distinguished from the males by their more prominent chest areas.[24] The individuals that hailed from the colder polar extremes of their planet were noticeably less colorful than those who came from the tropical zones.[7]

    The Mon Calamari were vigorous swimmers and were capable of living underwater for long periods.[6]
  </p></div>
  <div class="col-sm-1 col-md-5">
    <ul>
      <li><b>Real Name:</b> {{ user.first_name }} {{ user.last_name }}
      <li><b>Member Since:</b> {{ user.created.strftime('%m/%d/%Y') }}</li>
      <li><b>Paddle Log:</b><a href="{{ url_for('social.paddle_log', alias=user.alias) }}"> 18 entries this year</a></li>
      <li><b>Recent Trips:</b> {{ user.created.strftime('%m/%d/%Y') }}</li>
    </ul>
  </div>
</div>
{% else %}
  <h2>There doesn't appear to be a river here ... <span onclick="addRiver()">Add One!</span></h2>
{% endif %}
<div>{{ url_for('static', filename='CSS/iwbt.css') }}<div>
</div>

{% endblock %}