iwbt/models/__init__.py
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()

class Model(object):

    @property
    def shallow_json(self):
        return {k: v for k, v in self.__dict__.iteritems() if k not in "_sa_instance_state"}

iwbt/models/rivers.py
"""
    River Module contains class River
    Interacts with dataBase, Model for creating, accessing, and updating entries in Iwbt.Rivers
"""
from datetime import datetime
from sqlalchemy import Column, DateTime, Float, ForeignKey, Integer, String, Table, UniqueConstraint
from sqlalchemy.orm import relationship
from . import Base, Model


associate_user_favorites = Table('FavoriteRivers', Base.metadata,
                                 Column('id', Integer, primary_key=True),
                                 Column('user_id', Integer, ForeignKey('Users.id')),
                                 Column('river_id', Integer, ForeignKey('Rivers.id')))


class Area(Base, Model):
    __tablename__ = 'Areas'
    __table_args__ = (UniqueConstraint('name', name='_area_name_uc'),)
    id = Column(Integer, primary_key=True)
    name = Column(String(64), nullable=False)
    created = Column(DateTime, default=datetime.now)
    updated = Column(DateTime, default=datetime.now, onupdate=datetime.now)

    rivers = relationship('River', backref='area', cascade="all, delete, delete-orphan")
    sections = relationship('Section', backref='area', cascade="all, delete, delete-orphan")

    def __repr__(self):
        return "<Area: %r>" % self.name


class Gauge(Base, Model):
    __tablename__ = 'Gauges'
    id = Column(Integer, primary_key=True)
    usgs_id = Column(Integer, nullable=True)
    name = Column(String(64), nullable=False)
    river_id = Column(Integer, ForeignKey('Rivers.id'))
    created = Column(DateTime, default=datetime.now)
    updated = Column(DateTime, default=datetime.now, onupdate=datetime.now)

    river = relationship('River', backref='gauges', uselist=False)
    data = relationship('GaugeData', backref="gauge", order_by="desc(GaugeData.timestamp)")

    @property
    def current_level(self):
        return self.data[0]

    def get_current_flow(self, flow_type='level'):
        """ method to get current flow from USGS.
        :param flow_type: 'level' or 'flow' -- return level in feet or flow in CFS """
        return 100

    def __repr__(self):
        return "<Gauge: %r>" % self.name


class GaugeData(Base, Model):
    __tablename__ = 'GaugeData'
    __table_args__ = (UniqueConstraint('gauge_id', 'timestamp', name="UQ_GaugeData_gauge_id__timestamp"), )
    id = Column(Integer, primary_key=True)
    gauge_id = Column(Integer, ForeignKey('Gauges.id'))
    timestamp = Column(DateTime, default=datetime.now)
    retrieved = Column(DateTime, default=datetime.now)
    level = Column(Float)
    flow_cfs = Column(Float)

    def __repr__(self):
        return "<GaugeData: %r (%r)>" % (self.gauge.name, self.timestamp.strftime('%Y-%m-%d %H:%M:%S'))


class Rapid(Base, Model):
    __tablename__ = 'Rapids'
    id = Column(Integer, primary_key=True)
    name = Column(String(64), nullable=False)
    river_id = Column(Integer, ForeignKey('Rivers.id'), nullable=False)
    section_id = Column(Integer, ForeignKey('Sections.id'), nullable=False)
    rating = Column(Float)
    created = Column(DateTime, default=datetime.now)
    updated = Column(DateTime, default=datetime.now, onupdate=datetime.now)

    def __repr__(self):
        return "<Rapid: %r on %r>" % (self.name, self.river.name)


class River(Base, Model):
    __tablename__ = 'Rivers'
    id = Column(Integer, primary_key=True)
    name = Column(String(64), nullable=False)
    area_id = Column(Integer, ForeignKey('Areas.id'))
    created = Column(DateTime, default=datetime.now)
    updated = Column(DateTime, default=datetime.now, onupdate=datetime.now)

    rapids = relationship('Rapid', backref='river', cascade="all, delete, delete-orphan")
    sections = relationship('Section', backref='river', cascade="all, delete, delete-orphan")

    @property
    def primary_gauge(self):
        if self.gauges:
            return self.gauges[0]
        else:
            return None

    @property
    def json(self):
        json = {k: v for k, v in self.__dict__.iteritems() if k not in "_sa_instance_state"}
        if self.area:
            json['area'] = self.area.shallow_json
        if self.rapids:
            json['rapids'] = [r.shallow_json for r in self.rapids]
        if self.primary_gauge:
            json['gauge'] = self.primary_gauge.shallow_json
        if self.sections:
            json['sections'] = [s.shallow_json for s in self.sections]
        return json

    @property
    def current_data(self):
        if self.primary_gauge:
            return {'level': self.primary_gauge.current_level.level,
                    'flow': self.primary_gauge.current_level.flow_cfs,
                    'timestamp': self.primary_gauge.current_level.timestamp }
        return {'flow': None, 'level': None, 'timestamp': datetime.now()}

    def __repr__(self):
        return "<River: %r>" % (self.name)



class Section(Base, Model):
    __tablename__ = 'Sections'
    id = Column(Integer, primary_key=True)
    name = Column(String(64), nullable=False)
    area_id = Column(Integer, ForeignKey('Areas.id'))
    river_id = Column(Integer, ForeignKey('Rivers.id'), nullable=False)
    gauge_id = Column(Integer, ForeignKey('Gauges.id'))
    created = Column(DateTime, default=datetime.now)
    updated = Column(DateTime, default=datetime.now, onupdate=datetime.now)

    rapids = relationship('Rapid', backref='section', cascade="all, delete, delete-orphan")
    gauge = relationship('Gauge', backref='sections', uselist=False)

    def __repr__(self):
        return "<Section: %r %r>" % (self.river.name, self.name)

iwbt/models/weather.py
"""
    Weather Module contains data models for precipitation and associated data
"""
from datetime import datetime
from sqlalchemy import Column, DateTime, Float, ForeignKey, Integer, String, Table
from sqlalchemy.orm import relationship
from . import Base, Model


class WeatherStation(Base):
    __tablename__ = 'WeatherStations'
    id = Column(Integer, primary_key=True)
    source_id = Column(Integer, ForeignKey('WeatherSources.id'))
    latitude = Column(Float)
    longitude = Column(Float)

iwbt/blueprints/social/forms.py
from flask_wtf import FlaskForm
from wtforms import PasswordField, StringField, SubmitField
from wtforms.validators import DataRequired, EqualTo

class LoginForm(FlaskForm):
    alias = StringField('User Name', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    submit = SubmitField('Sign In')


class SignUpForm(FlaskForm):
    alias = StringField('User Name', validators=[DataRequired()])
    first_name = StringField('First Name', validators=[DataRequired()])
    last_name = StringField('Last Name', validators=[DataRequired()])
    email = StringField('Email', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired(), EqualTo('confirm', message='Passwords must match')])
    confirm = PasswordField('Confirm Password', validators=[DataRequired()])
    submit = SubmitField('Sign Me Up!')

iwbt/__init__.py
import os

from flask import Flask, g
from flask_bootstrap import Bootstrap
from flask_login import LoginManager
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker

from config import config
from .models import Base
from .models.social import User

login_manager = LoginManager()
bootstrap = Bootstrap()

def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])

    bootstrap.init_app(app)
    login_manager.init_app(app)

    from iwbt.blueprints.api_01 import api_01
    from . blueprints.main.views import main
    from . blueprints.rivers.views import rivers
    from . blueprints.social.views import social

    app.register_blueprint(rivers, url_prefix='/river')
    app.register_blueprint(social, url_prefix='/user')
    app.register_blueprint(main, url_prefix='/')
    app.register_blueprint(api_01, url_prefix='/api/v1.0')

    with app.app_context():
        get_db(app)


    @login_manager.user_loader
    def load_user(user_id):
        session = get_session(app)
        return session.query(User).filter(User.id == user_id).first()


    return app


def get_db(app):
    if not hasattr(g, 'dbcon'):
        g.dbcon = connect(app)
    return g.dbcon


def get_session(app):
    Session = sessionmaker(bind=get_db(app))
    return Session()


def connect(app):
    if os.getenv('DATABASE_URL'):
        eng = create_engine(os.getenv('DATABASE_URL'))
    else:
        eng = create_engine(app.config['DATABASE_URI'])
    if app.config['CREATE_DB']:
        Base.metadata.create_all(eng)
    return eng

iwbt/blueprints/api_01/__init__.py
"""
    River-API Stuff
    ==========================================
    API code is organized into sections based on the resource. Each resource
    has the following mandatory methods.

    Create new instance of resource
    ------------------------------------------
      * URL:        /api/v1.0/resource
      * Method:     POST
      * Route:      create_resource()
      * Returns:    shallow JSON-serialization of successfully-added resource
      * Required:   True

    Get Single Resource by numeric identifier
    ------------------------------------------
      * URL:        /api/v1.0/resource/<int:resource_id>
      * Method:     GET
      * Route:      read_resource_by_id(resource_id)
      * Returns:    single JSON-serialized object
      * Required:   True

    Get single resource by name string
    ------------------------------------------
      * URL:        /api/v1.0/resource/<string:resource_name>
      * Method:     GET
      * Route:      read_resource_by_name(resource_name)
      * Returns:    full JSON-serialized object
      * Required:   False
      * Note:       This only really applies to things that one may want to
                    look up by name, like River ...
                    top-level items.

    Get all resources of a particular type
    ------------------------------------------
      * URL:        /api/v1.0/resources/
      * Method:     GET
      * Route:      read_resources()
      * Returns:    array of JSON-serialized objects
      * Required:   True

    Update single resource by numeric identifier
    ------------------------------------------
      * URL:        /api/v1.0/resource/<int:resource_id>
      * Method:     PUT
      * Route:      update_resource(resource_id)
      * Returns:    shallow JSON-serialization of successfully-updated
                    resource instance
      * Required:   True

    Delete single resource by numeric identifier
    ------------------------------------------
      * URL:        /api/v1.0/resource/<int:resource_id>
      * Method:     DELETE
      * Route:      delete_resource(resource_id)
      * Returns:    200

    Full list of available resources
    ==========================================
    Each resource, along with a brief description, is provided below

    River
    Area
    Gauge
    GaugeData
    User

"""
from flask import Blueprint

api_01 = Blueprint('api_01', __name__, url_prefix='api/v1.0')


def verify(json, required_fields, allowed_fields=None):
    if not allowed_fields:
        allowed_fields = []
    allowed_fields += required_fields
    passes_required = verify_required_fields(json, required_fields)
    passes_allowed = verify_allowed_fields(json, allowed_fields)
    return passes_required * passes_allowed


def verify_required_fields(json, expected_fields):
    for field in expected_fields:
        try:
            assert field in json
        except AssertionError:
            return False
    return True


def verify_allowed_fields(json, allowed_fields):
    """ Ensure that no fields are passed that are not permitted for a
        given resource.
        :param json: dictionary of POST data passed in request
        :param allowed_fields: list of strings of acceptable parameters
        :return: True if all parameters are allowed; else False
    """
    for k in json.keys():
        if k not in allowed_fields:
            return False
    return True


def error_out(error):
    return error.json_response(True)


from . resources.areas import (create_area, read_area_by_id, read_areas,
                               update_area, delete_area)
from . resources.flow import (create_gauge_data, check_flow_by_river_id)
from . resources.gauges import (create_gauge, read_gauge_by_id, read_gauges,
                                update_gauge, delete_gauge)
from . resources.rapids import (create_rapid)
from . resources.rivers import (create_river, read_river_by_id,
                                read_river_by_name, read_rivers, update_river,
                                delete_river)
from . resources.sections import (create_section)
from . resources.users import (get_log_by_id, get_user_by_id,
                               get_user_by_alias, get_user_logs_by_id,
                               get_user_logs_by_alias, add_log_entry,
                               add_favorite_river)

iwbt/blueprints/main/views.py
from flask import Blueprint, current_app, render_template, send_file
from flask import redirect, request, url_for, flash

from flask_login import login_user, logout_user, login_required, current_user

from iwbt import get_session
from iwbt.models.rivers import *

main = Blueprint('main', __name__, url_prefix='')


@main.route('/')
def index():
    session = get_session(current_app)
    return render_template('index.html')



@main.route('ng')
def angular():
    return send_file('templates/ngtest.html')

iwbt/blueprints/rivers/views.py
from flask import Blueprint, current_app, render_template, redirect, request, url_for, flash

from flask_login import login_user, logout_user, login_required, current_user

from iwbt import get_session
from iwbt.models.rivers import *

rivers = Blueprint('rivers', __name__, url_prefix='river')


@rivers.route('/list')
def river_list():
    session = get_session(current_app)
    rivers = session.query(River).all()
    return render_template('rivers/river_list.html', rivers=rivers)


@rivers.route('/<int:river_id>')
def river_page(river_id):
    session = get_session(current_app)
    river = session.query(River).filter(River.id == river_id).first()
    return render_template('rivers/river_main.html', river=river)


@rivers.route('/favorites')
@login_required
def favorites():
    session = get_session(current_app)
    return render_template('rivers/river_list.html', rivers=current_user.favorite_rivers)

iwbt/blueprints/social/views.py
from flask import Blueprint, current_app, render_template, redirect, request, url_for, flash
from flask_login import login_user, logout_user, login_required, current_user
from sqlalchemy import or_

from iwbt import get_session
from iwbt.blueprints.social.forms import LoginForm, SignUpForm
from iwbt.models.social import *


social = Blueprint('social', __name__, url_prefix='user')


@social.route('/<user>')
def user_page(user):
    session = get_session(current_app)
    user = session.query(User).filter(User.alias == user).first()
    return render_template('social/user.html', user=user)


@social.route('/login', methods=['GET', 'POST'])
def login():
    session = get_session(current_app)
    login_form = LoginForm()

    if login_form.validate_on_submit():
        user = session.query(User).filter(User.alias == login_form.alias.data).first()
        if user is not None and user.verify_password(login_form.password.data):
            flash('You have successfully logged in to account %s' % user.alias, 'alert alert-success')
            login_user(user)
            return redirect(request.args.get('next') or url_for('social.user_page', user=user.alias))
        else:
            flash('UserName or Password Incorrect. Go Away :(', 'alert alert-danger')
        session.close()
        return redirect(url_for('social.login'))
    return render_template('social/login.html', form=login_form)


@social.route('/logout')
@login_required
def logout():
    logout_user()
    flash('You have been logged out', 'alert alert-danger')
    return redirect(url_for('river', name='Chattooga'))


@social.route('/signup', methods=['GET', 'POST'])
def sign_up():
    session = get_session(current_app)
    suf = SignUpForm()

    if suf.validate_on_submit():
        user = session.query(User).filter(or_(User.alias == suf.alias.data, User.email == suf.email.data)).first()
        if user:
            flash('User Name or Email already taken', 'alert alert-danger')
            return redirect("{{ url_for(social.sign_up) }}")
        flash('You have successfully signed up for an account with username %s' % suf.alias.data, 'alert alert-success')
        user = User(alias=suf.alias.data,
                    first_name=suf.first_name.data,
                    last_name=suf.last_name.data,
                    email=suf.email.data,
                    password=suf.password.data)
        session.add(user)
        session.commit()
        return redirect(url_for('social.login'))
    return render_template('social/signup.html', form=suf)


@social.route('/<alias>/log')
def paddle_log(alias):
    session = get_session(current_app)
    u = session.query(User).filter(User.alias == alias).first()
    return render_template('social/paddlelog.html', user=u)

iwbt/templates/rivers/favorites.html
{% extends "base.html" %}
<title>{% block title %}Find Your River{% endblock %}</title>

{% block css %}
{{ super() }}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='river_main.css') }}">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/sweetalert2/6.6.2/sweetalert2.min.css">
{% endblock %}

{% block scripts %}
{{ super() }}
<script src="https://cdn.jsdelivr.net/sweetalert2/6.6.2/sweetalert2.min.js"></script>
{% endblock %}

{% block content %}
<!--<content framework for a river page TODO: need to make this flexible so it works for any river> -->
<div class="container" id="page_head">
{% if current_user.favorite_rivers %}
{% for river in current_user.favorite_rivers %}
  <div class="river-item">
    <h2>{{river.name}}</h2>
    <h4>Placeholder</h4>
  </div>
{% endfor %}
{% else %}
  <h2>It ain't nothin' but the biggest fuckin' river in the state. <span class="js-clickable" onclick="addRiver()">Add One!</span></h2>
{% endif %}
</div>

<script>
function addRiver() {
  swal({
  title: 'Add a new river ... but not THE New River',
  html:
    '<span class="pull-left">Name</span><input id="swal-input1" class="swal2-input">' +
    '<span class="pull-left">Area</span><input id="swal-input2" class="swal2-input">',
  preConfirm: function () {
    return new Promise(function (resolve) {
      resolve([
        $('#swal-input1').val(),
        $('#swal-input2').val()
      ])
    })
  },
  onOpen: function () {
    $('#swal-input1').focus()
  }
  }).then(function (result) {
    $.ajax({
      url: "{{ url_for('api_01.add_river') }}",
      type: "POST"
    })
  }).catch(swal.noop)
}
</script>
{% endblock %}

iwbt/templates/rivers/river_list.html
{% extends "base.html" %}
<title>{% block title %}Find Your River{% endblock %}</title>

{% block css %}
{{ super() }}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='river_main.css') }}">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/sweetalert2/6.6.2/sweetalert2.min.css">
<link rel="stylesheet" href="https://cdn.datatables.net/1.10.15/css/jquery.dataTables.min.css">
{% endblock %}

{% block scripts %}
{{ super() }}
<script src="https://cdn.jsdelivr.net/sweetalert2/6.6.2/sweetalert2.min.js"></script>
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>
{% endblock %}

{% block content %}
<!--<content framework for a river page TODO: need to make this flexible so it works for any river> -->
<div class="container" id="page_head">
{% if rivers %}
<table id="river-table" class="table table-striped table-bordered table-hover">
  <thead>
    <tr><td>Name</td><td>Area</td><td>Gauge</td><td>Last Updated</td><td>Current Level</td><td>Current Flow</td></tr>
  </thead>
  <tbody>
{% for river in rivers %}
  <tr class="info">
    <td><a href="{{ url_for('rivers.river_page', river_id=river.id) }}">{{river.name}}</a></td>
    <td>{{ river.area.name }}</td>
    <td>{{ river.primary_gauge }}</td>
    <td>{{ river.current_data['timestamp'].strftime('%m/%d/%Y %H:%M:%S')}}</td>
    <td>{{ river.current_data['level'] }} feet</td>
    <td>{% if river.current_data['flow'] %}{{ "{:.0f}".format(river.current_data['flow']) }} cfs{% endif %}</td>
  </tr>
{% endfor %}
</tbody>
{% else %}
  <h2>It ain't nothin' but the biggest fuckin' river in the state.<span onclick="addRiver()">Add One!</span></h2>
{% endif %}
</div>

<script>
$(document).ready(function() {
    $('#river-table').DataTable();
} );

function addRiver() {
  swal({
  title: 'Add a new river ... but not THE New River',
  html:
    '<span class="pull-left">Name</span><input id="swal-input1" class="swal2-input">' +
    '<span class="pull-left">Area</span><input id="swal-input2" class="swal2-input">',
  preConfirm: function () {
    return new Promise(function (resolve) {
      resolve([
        $('#swal-input1').val(),
        $('#swal-input2').val()
      ])
    })
  },
  onOpen: function () {
    $('#swal-input1').focus()
  }
  }).then(function (result) {
    $.ajax({
      url: "{{ url_for('api_01.create_river') }}",
      type: "POST"
    })
  }).catch(swal.noop)
}
</script>
{% endblock %}

iwbt/templates/rivers/river_main.html
{% extends "base.html" %}
<title>{% block title %}{{river.river_name}}{% endblock %}</title>

{% block css %}
{{ super() }}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='river_main.css') }}">
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='CSS/river.css') }}">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/sweetalert2/6.6.2/sweetalert2.min.css">
{% endblock %}

{% block scripts %}
{{ super() }}
<script src="https://cdn.jsdelivr.net/sweetalert2/6.6.2/sweetalert2.min.js"></script>
{% endblock %}

{% block content %}
<!--<content framework for a river page -- TODO: need to make this flexible so it works for any river> -->
<div class="page-container" id="page_head">
  <div class="page-wrapper">
    <div class="sidebar collapse in width">
      <div class="sidebar-content panel-group">
        <div class="panel panel-default">
          <div class="panel-heading">
            <div class="panel-title"><a href="#overview">Overview</a></div>
            {% if river.sections %}
              {% for section in river.sections %}
                <div class="panel-title"><a data-toggle="collapse" href="#collapse{{ section.id }}">{{ section.name }}</a></li>
                  {% if section.rapids %}
                    <div id="collapse{{ section.id }}" class="panel-collapse collapse">
                      <ul class="list-group">
                        {% for rapid in section.rapids %}
                          <li class="list-group-item"><a href="#rapid{{ rapid.id }}">{{ rapid.name }}</a></li>
                        {% endfor %}
                      </ul>
                    </div>
                  {% endif %}
                </div>
              {% endfor %}
            {% endif %}
          </div>
        </div>
      </div>
    </div>
    <div class="page-content">
    {% if river %}
      <h2 id="page_title">{{river.name}}</h2>
      <!--<h4 id="river_description" style="font-size:2.5vw">Placeholder</h4>-->
      <div>
        {% if river.gauges %}
        <ul>
          {% for gauge in river.gauges %}
            <li>{{ gauge.name }}: {{ gauge.current_level.level }}</li>
          {% endfor %}
        </ul>
        {% endif %}

        {% if river.sections %}
        {% for section in river.sections %}
        <h3>{{ section.name }}</h3>
          {% if section.rapids %}
          <ul class="rapid-list">
            {% for rapid in section.rapids %}
              <li><span class="rating">{{ rapid.rating }}</span><span class="rapid-name"><a href="#">{{ rapid.name }}</a></span></li>
            {% endfor %}
          </ul>
          {% endif %}
        {% endfor %}
        {% endif %}
      </div>
    {% else %}
      <h2>There doesn't appear to be a river here ... <span onclick="addRiver()">Add One!</span></h2>
    {% endif %}
    </div>
  </div>
</div>
{% endblock %}

iwbt/templates/rivers/select_river.html
{% extends "base.html" %}

<title>{% block title %}Select Rivers{% endblock %}</title>

{% block content %}
    <!--<put some comments here about what's going on> -->
    <div class="container" style="margin: 10px;">
        <h2 style="margin-top: 50px">Select A River</h2>
        <div class="list-group" id="#river_drawers">
            {% for o in river_list %}
                <a href="/river/{{ o.get_url }}" class="list-group-item" style="background-color:#99FF99">
                    <h4 class="list-group-item-heading">{{o.river_name}}</h4>
                    <p class="list-group-item-text">{{o.section_name}}  - 
			{{o.short_description}}</p>
                </a>

            {% endfor %}
        </div>
    </div>
{% endblock %}